GLASSDOOR_USR = "place user name here"
GLASSDOOR_PSD = "place password here"
DB_URL = "place database url here"
DB_USR = "place database master username here"
DB_PWD = "place database password here"

assert GLASSDOOR_USR != "place user name here", "Must enter credentials in creds.py!"
assert GLASSDOOR_PSD != "place password here", "Must enter credentials in creds.py!"
assert DB_URL != "place database url here", "Must enter credentials in creds.py!"
assert DB_USR != "place database master username here", "Must enter credentials in creds.py!"
assert DB_PWD != "place database password here", "Must enter credentials in creds.py!"
